#!/usr/bin/env bash

source ../functions.sh

set_wallpaper 0 scaled wallpaper.jpg
kill_polybar
(
  flock 200
  start_bar eDP1 4k
) 200>/var/tmp/polybar-launch.lock
xinput --map-to-output 'ELAN Touchscreen' eDP1
