#!/usr/bin/env bash

source ../functions.sh

kill_polybar
set_wallpaper 0 scaled IMG_20190901_161515-PANO.jpg
set_wallpaper 1 auto IMG_20190903_163002-EFFECTS.jpg
(
  flock 200
  start_bar DP-1 1080p
  start_bar DP-2 1080p
) 200>/var/tmp/polybar-launch.lock

move_ws 4 left
move_ws 5 left
