#!/usr/bin/env bash

source ../functions.sh

kill_polybar
set_wallpaper 0 scaled IMG_20190901_161515-PANO.jpg
set_wallpaper 1 auto IMG_20190903_163002-EFFECTS.jpg
set_wallpaper 2 zoom-fill IMG_20190730_155936-PANO.jpg
(
  flock 200
  start_bar eDP-1 1080p
  start_bar DP-2 4k
) 200>/var/tmp/polybar-launch.lock

move_ws 2 left
