# pets: package=zsh
# pets: symlink=~/.zshrc
#
# Warning! This file has been generated by pets(1). Any manual modification
# will be lost.

for file in ${HOME}/.dotfiles/zsh.d/*.zsh; do
  # shellcheck disable=SC1091
  # shellcheck source=~/.dotfiles/zsh/*.zsh
  source "$file"
done
fpath=(~/.dotfiles/zsh-completions $fpath)
source "$HOME/.zprofile"
