#!/usr/bin/env bash

if [[ $DEBUG == 'true' ]]; then
  set -euxo pipefail
else
  set -euo pipefail
fi
IFS=$'\n\t'

move_ws() {
  WORKSPACE=$1
  DIRECTION=$2
  i3-msg workspace "$WORKSPACE"
  i3-msg move workspace to output "$DIRECTION"
}

kill_polybar() {
  pkill polybar || true
  # Wait until the processes have been shut down
  while pgrep -x polybar >/dev/null; do sleep 1; done
}

start_bar() {
  export MONITOR=$1
  BAR=$2
  polybar --reload "$BAR" </dev/null >"/var/tmp/polybar-$MONITOR.log" 2>&1 &
}

set_wallpaper() {
  SCREEN=$1
  MODE=$2
  IMAGE=$3
  nitrogen --head="$SCREEN" --set-"$MODE" --save ~/pictures/wallpapers/"$IMAGE"
}

postswitch() {
  kill_polybar
  set_wallpaper 1 scaled IMG_20190901_161515-PANO.jpg
  set_wallpaper 0 auto EFFECTS.jpg
  (
    flock 200
    start_bar DP-2 1080p
    start_bar HDMI-1 1080p
  ) 200>/var/tmp/polybar-launch.lock

  move_ws 1 left
  move_ws 2 left
  move_ws 3 left
}

postswitch
