local Plug = vim.fn["plug#"]

vim.call("plugins#PlugLoad")
vim.call("plug#begin", "~/.local/share/nvim")

Plug("MeanderingProgrammer/render-markdown.nvim")
Plug("MunifTanjim/nui.nvim")
Plug("nickjvandyke/opencode.nvim")
Plug("WhoIsSethDaniel/mason-tool-installer.nvim")
Plug("Yggdroot/indentLine")
Plug("cespare/vim-toml", { ["for"] = "toml" })
Plug("chrisbra/csv.vim", { ["for"] = "csv" })
Plug("christoomey/vim-tmux-navigator")
Plug("ekalinin/Dockerfile.vim", { ["for"] = [['Dockerfile', 'docker-compose']] })
Plug("elzr/vim-json")
Plug("fatih/vim-go", { ["do"] = ":GoInstallBinaries", ["for"] = [['go', 'gohtmltmpl']] })
Plug("folke/snacks.nvim")
Plug("godlygeek/tabular")
Plug("google/vim-jsonnet")
Plug("gregsexton/gitv")
Plug("hashivim/vim-terraform")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-cmdline")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-path")
Plug("hrsh7th/cmp-vsnip")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/vim-vsnip")
Plug("ibhagwan/fzf-lua")
Plug("leafgarland/typescript-vim", { ["for"] = [['typescript.tsx', 'typescriptreact', 'typescript', 'vue']] })
Plug("lewis6991/gitsigns.nvim")
Plug("mason-org/mason-lspconfig.nvim", { ["tag"] = "v2.1.0" })
Plug("mason-org/mason.nvim", { ["tag"] = "v2.2.1" })
Plug("mhinz/vim-startify")
Plug("moll/vim-node")
Plug("mrcjkb/rustaceanvim")
Plug("neovim/nvim-lspconfig")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim", { ["tag"] = "0.1.8" })
Plug("nvim-tree/nvim-web-devicons")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("pangloss/vim-javascript", { ["for"] = [['typescript.tsx', 'typescriptreact', 'javascript', 'vue']] })
Plug("rust-lang/rust.vim", { ["for"] = "rust" })
Plug("ryanoasis/vim-devicons")
Plug("scrooloose/nerdcommenter")
Plug("nvim-neo-tree/neo-tree.nvim", { ["branch"] = "v3.x" })
Plug("sheerun/vim-polyglot")
Plug("sickill/vim-monokai")
Plug("stevearc/conform.nvim")
Plug("tpope/vim-fugitive")
Plug("tpope/vim-surround")
Plug("vim-airline/vim-airline")
Plug("vim-airline/vim-airline-themes")
Plug("zbirenbaum/copilot-cmp")
Plug("zbirenbaum/copilot.lua")

vim.call("plug#end")
