local Plug = vim.fn["plug#"]

vim.call("plugins#PlugLoad")
vim.call("plug#begin", "~/.local/share/nvim")

-- Plug("github/copilot.vim")
Plug("WhoIsSethDaniel/mason-tool-installer.nvim")
Plug("Xuyuanp/nerdtree-git-plugin")
Plug("Yggdroot/indentLine")
Plug("cespare/vim-toml", { ["for"] = "toml" })
Plug("chrisbra/csv.vim", { ["for"] = "csv" })
Plug("christoomey/vim-tmux-navigator")
Plug("ekalinin/Dockerfile.vim", { ["for"] = [['Dockerfile', 'docker-compose']] })
Plug("ellisonleao/glow.nvim")
Plug("elzr/vim-json")
Plug("fatih/vim-go", { ["do"] = ":GoInstallBinaries", ["for"] = [['go', 'gohtmltmpl']] })
Plug("frankroeder/parrot.nvim")
Plug("godlygeek/tabular")
Plug("google/vim-jsonnet")
Plug("gregsexton/gitv")
Plug("hashivim/vim-terraform")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-cmdline")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-path")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/vim-vsnip")
Plug("ibhagwan/fzf-lua")
Plug("leafgarland/typescript-vim", { ["for"] = [['typescript.tsx', 'typescriptreact', 'typescript', 'vue']] })
Plug("lewis6991/gitsigns.nvim")
Plug("mhinz/vim-startify")
Plug("moll/vim-node")
Plug("mrcjkb/rustaceanvim")
Plug("neovim/nvim-lspconfig")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim", { ["tag"] = "0.1.x" })
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("nvim-treesitter/nvim-treesitter-refactor")
Plug("pangloss/vim-javascript", { ["for"] = [['typescript.tsx', 'typescriptreact', 'javascript', 'vue']] })
Plug("rust-lang/rust.vim", { ["for"] = "rust" })
Plug("ryanoasis/vim-devicons")
Plug("scrooloose/nerdcommenter")
Plug("scrooloose/nerdtree")
Plug("sheerun/vim-polyglot")
Plug("sickill/vim-monokai")
Plug("stevearc/conform.nvim")
Plug("tpope/vim-fugitive")
Plug("tpope/vim-surround")
Plug("vim-airline/vim-airline")
Plug("vim-airline/vim-airline-themes")
Plug("williamboman/mason-lspconfig.nvim")
Plug("williamboman/mason.nvim")
Plug("wlangstroth/vim-racket")
Plug("zbirenbaum/copilot-cmp")
Plug("zbirenbaum/copilot.lua")

vim.call("plug#end")

require("glow").setup()

-- setup Copilot
require("copilot").setup({})
require("copilot_cmp").setup()
