alias sshon="sudo systemctl start ssh"
alias sshoff="sudo systemctl stop ssh"
alias getip="ip addr | awk '/inet/ {print }'"
alias ll="ls -al"
alias pgr="ps -ef | grep"
alias apti="sudo apt install"
alias aptu="sudo apt update"
alias apts="apt-cache search"
