#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../functions.sh"

kill_polybar
set_wallpaper 0 zoom-fill PXL_20221228_143940280-PANO.jpg
set_wallpaper 1 auto EFFECTS.jpg
(
	flock 200
	start_bar DP-1 1080p
	start_bar eDP-1 1080p
	move_ws 2 right
	move_ws 3 right
) 200>/var/tmp/polybar-launch.lock
